Fix panic when setting cargo-dir
cargo-update 20.0.2 would crash when cargo-dir was set with the following

```
thread 'main' (735889) panicked at src/options.rs:194:42:
Mismatch between definition and access of `cargo-dir`. Could not downcast to &std::path::PathBuf, need to downcast to std::path::PathBuf
```

This changes the sig of `cargo_dir` to take a `PathBuf` instead of a ref to a
`PathBuf`.